# Generated by Django 3.2 on 2023-05-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('employee_id', models.CharField(max_length=11, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('group', models.SmallIntegerField(choices=[(1, '超级管理员'), (2, '普通管理员')], verbose_name='用户组')),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('press', models.CharField(blank=True, max_length=30, null=True, verbose_name='出版社')),
                ('author', models.CharField(blank=True, max_length=60, null=True, verbose_name='作者')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='零售价格')),
                ('amount', models.IntegerField(default=0, verbose_name='库存数量')),
            ],
        ),
        migrations.CreateModel(
            name='SystemBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('type', models.SmallIntegerField(choices=[(1, '收入'), (2, '支出')], verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', to_field='username', verbose_name='操作用户')),
            ],
        ),
    ]
