# Generated by Django 3.2 on 2023-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('press', models.CharField(max_length=30, verbose_name='出版社')),
                ('author', models.CharField(max_length=60, verbose_name='作者')),
                ('retail_price', models.IntegerField(default=0, verbose_name='零售价格')),
                ('amount', models.IntegerField(default=0, verbose_name='零售价格')),
            ],
        ),
    ]
