# Generated by Django 3.2 on 2023-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='press',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='零售价格'),
        ),
    ]
