# Generated by Django 3.2 on 2023-05-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='username',
            field=models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', to_field='username', verbose_name='操作用户'),
        ),
    ]
