# Generated by Django 3.2 on 2023-05-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_bill_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 10:46:06', verbose_name='时间'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default='2023-05-05 10:46:06', verbose_name='创建时间')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='进货价格')),
                ('purchase_amount', models.IntegerField(verbose_name='进货数量')),
                ('state', models.SmallIntegerField(choices=[(1, '未付款'), (2, '已付款')], verbose_name='订单状态')),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', to_field='username', verbose_name='操作用户')),
            ],
        ),
    ]
