# Generated by Django 3.2 on 2023-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20230505_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 11:18:03', verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '未付款'), (2, '已付款')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 11:18:03', verbose_name='创建时间'),
        ),
    ]
