# Generated by Django 4.2.1 on 2023-05-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_bill_timestamp'),
    ]

    operations = [
    ]
