# Generated by Django 3.2 on 2023-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20230505_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 11:30:50', verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='进货价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '已取消')], default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 11:30:50', verbose_name='创建时间'),
        ),
    ]
