# Generated by Django 4.2.1 on 2023-05-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_bill_timestamp'),
    ]

    operations = [
    ]
