# Generated by Django 3.2 on 2023-05-05 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20230505_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 12:33:57', verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_amount',
            field=models.PositiveIntegerField(verbose_name='进货数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='进货价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 12:33:57', verbose_name='创建时间'),
        ),
    ]
