# Generated by Django 4.2.1 on 2023-05-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20230505_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 06:02:33', verbose_name='时间'),
        ),
    ]
