# Generated by Django 4.2.1 on 2023-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_bill_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default='2023-05-05 12:40:12', verbose_name='时间'),
        ),
    ]
