# Generated by Django 4.1.5 on 2023-05-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20230505_2107'),
        ('app01', '0015_alter_bill_timestamp'),
    ]

    operations = [
    ]
